loja/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

produto/urls.py
from django.urls import path
from . import views


app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProdutos.as_view(), name='detalhe'),

    path('adcionaroaocarrinho/', views.AdcionarAoCarrinho.as_view(), name='adicionaraocarrinho'),

    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('finalizar/', views.Finalizar.as_view(), name='finalizar'),

]

templates/parciais/_footer.html
{% load static %}


<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Luiz Otávio</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load static %}


<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="#">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>109x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/parciais/_pagination.html
{% if is_paginated %}
    <div class="pagination">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}