loja/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

produto/urls.py
from django.urls import path
from . import views


app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProdutos.as_view(), name='detalhe'),

    path('adcionaroaocarrinho/', views.AdcionarAoCarrinho.as_view(), name='adicionaraocarrinho'),

    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('finalizar/', views.Finalizar.as_view(), name='finalizar'),

]

produto/models.py
from django.conf import settings
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
from utils import utils


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=155)
    descricao_longa = models.TextField()
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField('Preço')
    preco_marketing_promocional = models.FloatField('Preço promo', default=0)
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)

    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return utils.formata_preco(self.preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço promo'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return
        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from . import models


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 12
    ordering = '-id'


class DetalheProdutos(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdcionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            messages.error(self.request, 'Erro ao adicionar o produto ao carrinho.')
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)

        if variacao.estoque < 1:
            messages.error(self.request, 'Estoque insuficiente.')
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = dict()
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variacao_id in carrinho:
            # TODO: Variação existe no carrinho
            pass
        else:
            carrinho[variacao_id] = {
                
            }

        return HttpResponse(f'{variacao.produto} {variacao.nome}')


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Remover do carrinho')


class Carrinho(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Carrinho')


class Finalizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Finalizar')

produto/templates/produto/detalhe.html
{% extends 'base.html'%}
{% load omfilters %}

{% block conteudo %}

<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if produto.imagem %}
                    <img class="img-fluid" src="{{ produto.imagem.url}}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{ produto.nome}}</h1>
            <p class="lead">{{ produto.descricao_curta }}</p>
            <p class="lead">
                {% if produto.preco_marketing_promocional %}
                    <span id="variation-preco-promocional" class="lead product-price">
                        {{ produto.preco_marketing_promocional | formata_preco }}
                    </span>
                    <span id="variation-preco" class="lead product-old-price text-muted">
                        {{ produto.preco_marketing | formata_preco }}
                    </span>
                {% else %}
                    <span id="variation-preco" class="lead product-price">
                        {{ produto.preco_marketing | formata_preco }}
                    </span>
                {% endif %}
            </p>

            <form action="{% url 'produto:adicionaraocarrinho'%}" id="form-add-to-cart">
                <div class="form-group">
                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                        {% for variacao in produto.variacao_set.all %}

                            {% if variacao.preco_promocional %}
                                <option data-preco="{{ variacao.preco | formata_preco }}"
                                    data-preco-promocional="{{ variacao.preco_promocional | formata_preco  }}"
                                    value="{{ variacao.id }}">
                                    {% if variacao.nome %}
                                        {{ variacao.nome }}
                                    {% else %}
                                        {{ variacao }}
                                    {% endif %}
                                </option>
                            {% else %}
                                <option data-preco="{{ variacao.preco | formata_preco }}" value="{{ variacao.id }}">
                                    {% if variacao.nome %}
                                        {{ variacao.nome }}
                                    {% else %}
                                        {{ variacao }}
                                    {% endif %}
                                </option>
                            {% endif %}

                        {% endfor %}

                    </select>
                </div>

                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>
            </form>
            
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ produto.nome }}</h2>
            {{ produto.descricao_longa | linebreaks }}
        </div>
    </div>
</div>
{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}

            <div class="card">

                {% if produto.imagem %}
                <a href="{{ produto.slug }} ">
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                </a>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text">{{ produto.descricao_curta }}</p>
                    <div class="container product-price-block text-center">

                        {% if produto.preco_marketing_promocional %}
                        <span class="product-price">
                            {{ produto.preco_marketing_promocional | formata_preco }}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.preco_marketing | formata_preco }}

                        </span>
                        {% else %}
                        <span class="product-price">
                            {{ produto.preco_marketing | formata_preco }}
                        </span>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{{ produto.slug }}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>


<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>
{% endblock %}